### ISSUE TITLE
PodDisruptionBudget Structure

### ISSUE THREAD

**Issue by nalum** [Nalum/cert-manager-module#18]
Looking at the definition of the PDB config structure:

https://github.com/Nalum/cert-manager-module/blob/763e31749b3b42a9128cda7976d3e67b89d506a6/templates/config/config.cue#L175-L179

As the fields `minAvailable` and `maxUnavailable` are mutually exclusive, I'm thinking it would be better to have this:

```cue
#PodDisruptionBudgetData: {
	enabled:         bool
	minAvailable:   int | #Percent
} | {
	enabled:         bool
	maxUnavailable: int | #Percent
}
```

This would require changes to the PDB resource definition:

https://github.com/Nalum/cert-manager-module/blob/763e31749b3b42a9128cda7976d3e67b89d506a6/templates/podDisruptionBudget.cue#L23-L34

And then the config setup:
https://github.com/Nalum/cert-manager-module/blob/763e31749b3b42a9128cda7976d3e67b89d506a6/templates/config/config.cue#L78-L86

As it would result in an error if either `minAvailable` or `maxUnavailable` are not set.

The current setup will fail at apply time, where timoni would validate the above. 

@stefanprodan @yyvess do either of you have thoughts on this?

**Comment by stefanprodan** [comment]
I think you can define it like this:

```cue
#OneOfPDB: {minAvailable: int} | {maxUnavailable: int}

#PodDisruptionBudgetData: {
	#OneOfPDB
	enabled:         bool
}

```

**Comment by nalum** [comment]
Yeah, that looks good. Did some testing with `timoni mod show config` and it was not happy with either of these. I ended up with the following:

```cue
#OneOfPDB: {minAvailable: int} | {maxUnavailable: int}

#PodDisruptionBudgetData: {
	enabled:         *false | true
	if enabled {
		#OneOfPDB
	}
}

```

But it's showing an issue with the parsing of the cue files in relation to the markdown generation table. If `enabled` is `false` then we don't get output for `minAvailable` or `maxUnavailable`, if it's `true` then we only get the one that's set.

**Comment by yyvess** [comment]
This kind of issues will occur each time we want to add some _intelligence_ on default values :-(

From my last change =>
- if _highAvailability_ is false => pdb are disable by default.
- if _highAvailability_ is true  => pdb are enable by default and minAvailable equals number of replicas - 1.
 
Personally I like the idea of the flag '_highAvailability_' that change default values. 
It's will really simplify the configuration for the end-user.

The _highAvailability_  flag is the equivalent to set these values =>
```
	controller: {
		replicas: 2
		podDisruptionBudget: {
			enabled:      true
			minAvailable: 1
		}
	}
	webhook: {
		replicas: 3
		podDisruptionBudget: {
			enabled:      true
			minAvailable: 2
		}
	}
	caInjector: {
		replicas: 2
		podDisruptionBudget: {
			enabled:      true
			minAvailable: 1
		}
	}
```
